image: gitpod/workspace-full-vnc:latest
tasks:
  - name: Setup Container
    init: >
      sudo apt-get --quiet update --yes
      sudo apt-get --quiet install --yes wget apt-utils tar zip unzip lib32stdc++6 lib32z1 build-essential ruby ruby-dev
      sudo apt-get --quiet install --yes vim-common
      sudo DEBIAN_FRONTEND=noninteractive apt-get install -y libgtk2.0-0 libgtk-3-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb  
      sudo apt-get --quiet install --yes chromium-browser
      sudo rm -rf /var/lib/apt/lists/*
      sudo apt-get clean -qq
      curl -s "https://get.sdkman.io" | bash
      echo "Tathir"
    command: >
      source "$HOME/.sdkman/bin/sdkman-init.sh"
# Ports to expose on workspace startup
ports:
  - port: 8000
    # onOpen: open-preview

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - CoenraadS.bracket-pair-colorizer
    - vscodevim.vim
    - christian-kohler.npm-intellisense
    - esbenp.prettier-vscode
    - Angular.ng-template
