image: gitpod/workspace-full-vnc:latest
tasks:
  - name: Container
    init: |
      sudo apt-get --quiet update --yes
      sudo apt-get --quiet install --yes wget apt-utils tar zip unzip lib32stdc++6 lib32z1 build-essential ruby ruby-dev
      sudo apt-get --quiet install --yes vim-common
      sudo DEBIAN_FRONTEND=noninteractive apt-get install -y libgtk2.0-0 libgtk-3-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb  
      sudo apt-get --quiet install --yes chromium-browser
      sudo apt-get --quiet install --yes apt-transport-https ca-certificates gnupg
      sudo apt-get --quiet install --yes
      gnupg software-properties-common curl
      sudo rm -rf /var/lib/apt/lists/*
      sudo apt-get clean -qq
      gp sync-done apt-get
      echo "Tathir INIT"
    command: |
      yes | sdk install java 8.0.332-zulu
      echo "Tathir COMMAND"
      
  - name: Android SDK
    init: |
      gp env ANDROID_TOOLS_URL="https://dl.google.com/android/repository/commandlinetools-linux-8092744_latest.zip"
      gp env ANDROID_API_VERSION="28"
      gp env ANDROID_BUILD_TOOLS="28.0.0"
      gp env ANDROID_HOME=/home/gitpod/android-sdk-linux
      gp env PATH=$PATH:$ANDROID_HOME/cmdline-tools:$ANDROID_HOME/cmdline-tools/bin
      gp env PATH=$PATH:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$ANDROID_HOME/platforms
      echo ">>"$ANDROID_HOME
      mkdir -p $ANDROID_HOME
      chmod -R 777 $ANDROID_HOME
      cd $ANDROID_HOME && echo $PWD && wget $ANDROID_TOOLS_URL && unzip -q *.zip -d $ANDROID_HOME && rm *.zip && echo $PWD
      yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_HOME --install "build-tools;${ANDROID_BUILD_TOOLS}"
      yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_HOME --install "platforms;android-${ANDROID_API_VERSION}"
      yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_HOME --install "platform-tools"
      yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_HOME --install "extras;android;m2repository"
      yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_HOME --install "extras;google;m2repository"
      yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_HOME --install "extras;google;google_play_services"
      
  - name: Google Cloud CLI
    init: |
      echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
      curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
      gp sync-await apt-get && sudo apt-get update && sudo apt-get install google-cloud-cli && gp sync-done apt-get
      
  
  - name: Terraform
    init: |
      curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
      sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      gp sync-await apt-get && sudo apt-get update && sudo apt-get install terraform && gp sync-done apt-get   

# Ports to expose on workspace startup
ports:
  - port: 8000
    # onOpen: open-preview

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - CoenraadS.bracket-pair-colorizer
    - vscodevim.vim
    - christian-kohler.npm-intellisense
    - esbenp.prettier-vscode
    - Angular.ng-template
