image: gitpod/workspace-full-vnc:latest
tasks:
  - name: Setup X11
    init: |
      sudo apt-get --quiet update --yes
      sudo apt-get --quiet install --yes \
      wget \
      apt-utils \
      tar \
      zip \
      unzip \
      lib32stdc++6 \
      lib32z1 \
      build-essential \
      ruby \
      ruby-dev
      echo "Tathir"

# Ports to expose on workspace startup
ports:
  - port: 8000
    # onOpen: open-preview

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - CoenraadS.bracket-pair-colorizer
    - vscodevim.vim
    - eamodio.gitlens
    - christian-kohler.npm-intellisense
    - esbenp.prettier-vscode
    - Angular.ng-template
