image: gitpod/workspace-full-vnc:latest
tasks:
  - name: Container
    init: |
      sudo apt-get --quiet update --yes
      sudo apt-get --quiet install --yes wget apt-utils tar zip unzip lib32stdc++6 lib32z1 build-essential ruby ruby-dev
      sudo apt-get --quiet install --yes vim-common
      sudo DEBIAN_FRONTEND=noninteractive apt-get install -y libgtk2.0-0 libgtk-3-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb  
      sudo apt-get --quiet install --yes chromium-browser
      sudo rm -rf /var/lib/apt/lists/*
      sudo apt-get clean -qq
      echo "Tathir INIT"
    command: |
      yes | sdk install java 8.0.332-zulu
      echo "Tathir COMMAND"
      
  - name: Android SDK
    init: |
      gp env ANDROID_TOOLS_URL="https://dl.google.com/android/repository/commandlinetools-linux-8092744_latest.zip"
      gp env ANDROID_API_VERSION="28"
      gp env ANDROID_BUILD_TOOLS="28.0.0"
      gp env ANDROID_HOME=/home/gitpod/android-sdk-linux
      gp env PATH=$PATH:$ANDROID_HOME/cmdline-tools:$ANDROID_HOME/cmdline-tools/bin
      gp env PATH=$PATH:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$ANDROID_HOME/platforms
      echo ">>"$ANDROID_HOME
      mkdir -p $ANDROID_HOME
      chmod -R 777 $ANDROID_HOME
      cd $ANDROID_HOME && echo $PWD && wget $ANDROID_TOOLS_URL && unzip -q *.zip -d $ANDROID_HOME && rm *.zip && echo $PWD
      yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_HOME --install "build-tools;${ANDROID_BUILD_TOOLS}"
#      cd $ANDROID_HOME && yes | sdkmanager --sdk_root=$ANDROID_HOME --install "platforms;android-${ANDROID_API_VERSION}"
#      cd $ANDROID_HOME && yes | sdkmanager --sdk_root=$ANDROID_HOME --install "platform-tools"
#      cd $ANDROID_HOME && yes | sdkmanager --sdk_root=$ANDROID_HOME --install "extras;android;m2repository"
#      cd $ANDROID_HOME && yes | sdkmanager --sdk_root=$ANDROID_HOME --install "extras;google;m2repository"
#      cd $ANDROID_HOME && yes | sdkmanager --sdk_root=$ANDROID_HOME --install "extras;google;google_play_services"

# Ports to expose on workspace startup
ports:
  - port: 8000
    # onOpen: open-preview

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - CoenraadS.bracket-pair-colorizer
    - vscodevim.vim
    - christian-kohler.npm-intellisense
    - esbenp.prettier-vscode
    - Angular.ng-template
